{{- if .Values.teamRoles.viewer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: owner
  labels:
    jenkins.io/kind: "EnvironmentRole"
  annotations:
     title: "Team Owner"
     description: "A team owner can add/remove users and has write access to all team resources"
rules:
  - apiGroups:
    - ""
    - extensions
    - apps
    - rbac.authorization.k8s.io
    - batch
    - jenkins.io
    - tekton.dev
    resources:
    - "*"
    - "pods/*"
    - deployments
    verbs:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
{{- end }}
